name = "yu"
main = "_worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat_v2"]

minify = true
workers_dev = true
routes = [
   
  { pattern = "ava.game.naver.com.yu.c6k7ql9g5b.workers.dev", custom_domain = true },
  { pattern = "collection.linefriends.com.yu.c6k7ql9g5b.workers.dev", custom_domain = true }
 
]




[unsafe.metadata.observability]
enabled = false

[observability.logs]
enabled = false
